name: First Workflow
on: push
jobs:
  do-some-test:
    runs-on: ubuntu-latest
    steps:
      - name: print to hello
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run react tests
        run: echo "tests is running"
      - name: print to goodbye
        run: echo "Goodbye"
  deploy:
    needs: [do-some-test]
    runs-on: ubuntu-latest
    steps:
      - name: print to hello
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: deploy to server
        run: echo "deploying"

      
