name: First Workflow
on:
 push:
  branches:
   - main
jobs:
 do-some-test:
  runs-on: ubuntu-latest
  steps:
   - name: print to hello
     run: echo "Hello World!"
   - name: get code
     uses: actions/checkout@v3
   - name: install node
     uses: actions/setup-node@v3
     with:
      node-version: 18
   - name: install dependencies
     run: npm ci
   - name: run react tests
     run: echo "tests is running"
   - name: print to goodbye
     run: echo "Goodbye"
 build:
  needs: [do-some-test]
  runs-on: ubuntu-latest
  steps:
   - name: print to hello
     run: echo "Hello World!"
   - name: get code
     uses: actions/checkout@v3
   - name: install node
     uses: actions/setup-node@v3
     with:
      node-version: 18
   - name: install dependencies
     run: npm ci
   - name: build project
     run: npm run build
   - name: build end
     run: echo "build success"
 deploy:
  needs: [build]
  runs-on: ubuntu-latest
  steps:
   - name: print to hello
     run: echo "Hello World!"
   - name: get code
     uses: actions/checkout@v3
   - name: deploy to server
     run: echo "sending to server"
   - name: deploy end
     run: echo "deploy success"
